### ISSUE TITLE
Sonos adapter seems to have stopped working

### ISSUE THREAD

**Issue by dhylands** [freaktechnik/sonos-adapter#6]
Whenever the sonos adapter starts, I now get these errors:
```
2019-04-04 10:32:37.421 INFO   : sonos: Loading add-on for sonos-adapter from /home/dhylands/moziot/.mozilla-iot/addons/sonos-adapter
2019-04-04 10:32:38.267 ERROR  : sonos: TypeError: Cannot read property 'ZoneGroup' of undefined
2019-04-04 10:32:38.268 ERROR  : sonos:     at GetZoneGroupState.then (/home/dhylands/moziot/.mozilla-iot/addons/sonos-adapter/node_modules/sonos/lib/services/ZoneGroupTopology.js:46:76)
2019-04-04 10:32:38.268 ERROR  : sonos:     at <anonymous>
2019-04-04 10:32:38.268 ERROR  : sonos:     at process._tickCallback (internal/process/next_tick.js:189:7)
2019-04-04 10:32:38.501 ERROR  : sonos: TypeError: Cannot read property 'ZoneGroup' of undefined
2019-04-04 10:32:38.501 ERROR  : sonos:     at GetZoneGroupState.then (/home/dhylands/moziot/.mozilla-iot/addons/sonos-adapter/node_modules/sonos/lib/services/ZoneGroupTopology.js:46:76)
2019-04-04 10:32:38.502 ERROR  : sonos:     at <anonymous>
2019-04-04 10:32:38.502 ERROR  : sonos:     at process._tickCallback (internal/process/next_tick.js:189:7)
2019-04-04 10:32:38.643 ERROR  : sonos: TypeError: Cannot read property 'ZoneGroup' of undefined
2019-04-04 10:32:38.644 ERROR  : sonos:     at GetZoneGroupState.then (/home/dhylands/moziot/.mozilla-iot/addons/sonos-adapter/node_modules/sonos/lib/services/ZoneGroupTopology.js:46:76)
2019-04-04 10:32:38.644 ERROR  : sonos:     at <anonymous>
2019-04-04 10:32:38.645 ERROR  : sonos:     at process._tickCallback (internal/process/next_tick.js:189:7)
```
I have 3 speakers, which is why I think it shows up 3 times.

**Comment by freaktechnik** [comment]
Raised upstream: https://github.com/bencevans/node-sonos/issues/407

**Comment by freaktechnik** [comment]
Alright, this is fixed upstream, battling against issues with the image libraries now, but that'll hopefully be resolved soon. After that I'll release a new version.
